### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by smseboo** [a0rtega/tickergram-bot#1]
This is a very nice application, already made a contribution, what password to use to unblock?
Thank you kindly

**Comment by a0rtega** [comment]
Hey @smseboo ,

I saw your contribution but you used a different sponsorship option, that's why the password wasn't sent automatically. Drop me an email and I'll share the password with you, thanks! Get my email address from http://ebfe.es/

**Comment by smseboo** [comment]
Good day sir, my tickergram stopped working, is there an issue on your side?

Thank you,
Sebastian

**Comment by a0rtega** [comment]
Hey @smseboo ,

There’s been some issues with yfinance, the library used to get market data.

I try to keep up with the changes, the public tickergram bot that I run works fine now. If you are running your own bot, use the dev branch for now.

If you have any other specific problem, let me know.

**Comment by smseboo** [comment]
Its was working great, as anticipated,
I will be making another contribution as soon as possible.
Thank you for the tickerbot.
Sebastian
